# Secret Manager: one entry per secret, naming d3-staging-<name>.
#
# Generated by Terraform : db password, airflow JWT secret, airflow API secret,
#                          airflow admin (web UI) password.
# User-supplied (var)    : OpenRouter API key, Airflow Fernet key. These default
#                          to "REPLACE_ME" so the first apply succeeds; replace
#                          with real values (a new version, or a real tfvars).
#
# secretAccessor is granted ONLY to the SAs that need each secret.

# ─── Generated values ───────────────────────────────────────────────────────
resource "random_password" "db" {
  length  = 32
  special = false # keep the value clean for psycopg conninfo / proxy URLs
}

resource "random_password" "airflow_jwt" {
  length  = 50
  special = false
}

resource "random_password" "airflow_api" {
  length  = 50
  special = false
}

resource "random_password" "airflow_admin" {
  length  = 24
  special = false
}

# ─── Secret containers ──────────────────────────────────────────────────────
resource "google_secret_manager_secret" "this" {
  for_each  = local.secret_ids
  secret_id = each.value

  replication {
    auto {}
  }
}

# ─── Secret versions ────────────────────────────────────────────────────────
# Generated secrets get their value straight from the random_password resources.
resource "google_secret_manager_secret_version" "db_master_password" {
  secret      = google_secret_manager_secret.this["db_master_password"].id
  secret_data = random_password.db.result
}

resource "google_secret_manager_secret_version" "airflow_jwt_secret" {
  secret      = google_secret_manager_secret.this["airflow_jwt_secret"].id
  secret_data = random_password.airflow_jwt.result
}

resource "google_secret_manager_secret_version" "airflow_api_secret" {
  secret      = google_secret_manager_secret.this["airflow_api_secret"].id
  secret_data = random_password.airflow_api.result
}

resource "google_secret_manager_secret_version" "airflow_admin_pw" {
  secret      = google_secret_manager_secret.this["airflow_admin_pw"].id
  secret_data = random_password.airflow_admin.result
}

# User-supplied secrets seed an initial version from the variable. When you
# later add the real value out-of-band (a new version), Terraform won't fight
# it — we only manage this first version's data.
resource "google_secret_manager_secret_version" "openrouter_api_key" {
  secret      = google_secret_manager_secret.this["openrouter_api_key"].id
  secret_data = var.openrouter_api_key
}

resource "google_secret_manager_secret_version" "airflow_fernet_key" {
  secret      = google_secret_manager_secret.this["airflow_fernet_key"].id
  secret_data = var.airflow_fernet_key
}

# ─── Per-secret accessor IAM ────────────────────────────────────────────────
# API needs only the DB password.
resource "google_secret_manager_secret_iam_member" "api_db_password" {
  secret_id = google_secret_manager_secret.this["db_master_password"].secret_id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.api.email}"
}

# Airflow VM needs all five it consumes plus the DB password.
resource "google_secret_manager_secret_iam_member" "airflow_access" {
  for_each = toset([
    "db_master_password",
    "openrouter_api_key",
    "airflow_fernet_key",
    "airflow_jwt_secret",
    "airflow_api_secret",
    "airflow_admin_pw",
  ])
  secret_id = google_secret_manager_secret.this[each.key].secret_id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.airflow.email}"
}
